#!/bin/bash
#
#  fusiond The FusionX server.
#
#
# chkconfig: 345 80 20
# description: fusiond
# processname: fusiond
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/fusiond, see below
if [ -f /etc/sysconfig/fusiond ]; then
        . /etc/sysconfig/fusiond
fi

RETVAL=0

prog=fusiond
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/fusiond
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/fusiond}

# fusiond defaults to /usr/bin/fusiond, override with BITCOIND_BIN
fusiond=${BITCOIND_BIN-/usr/bin/fusiond}

# fusiond opts default to -disablewallet, override with BITCOIND_OPTS
fusiond_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $fusiond $fusiond_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
